import test from 'node:test';import assert from 'node:assert/strict';
import {renderResultsPng} from '../src/png.ts';
import type {Measurement,Sample} from '../src/analysis.ts';
function fixture(mode:'test'|'game'):Measurement{
  const sample:Sample={time:0,hipX:500,hipY:300,ankleX:500,ankleY:800,legLength:500,fppa:0,pelvis:0,shoulder:0,visibility:1,depth:0,rawFppa:0,rawPelvis:0,rawShoulder:0,judgingFppa:0,phase:'STANDING',rep:1,attempt:1,valid:true};
  return {created:'2026-10-04T16:30:00Z',settings:{mode,difficulty:'hard',side:'left',targetReps:1,depthTarget:.3,beep:true},baseline:{hipX:500,hipY:300,ankleX:500,ankleY:800,legLength:500,samples:20},frames:[],reps:[{number:1,duration:1.23,maxDepth:.35,fppaAtBottom:-2,maxFppa:2,minFppa:-2,pelvisAtBottom:1,shoulderAtBottom:2,samples:[sample,{...sample,time:100,depth:.35},{...sample,time:1000}]}],rejected:2,interrupted:0,stoppedEarly:false,totalDuration:4.56,filterApplied:true,filterHz:30};
}
function canvas(){const text:any[]=[],lines:any[]=[],fills:any[]=[],dashes:any[]=[];const ctx:any={fillText:(...s:any[])=>text.push(s),fillRect:(...s:any[])=>fills.push([ctx.fillStyle,...s]),beginPath:()=>{},moveTo:(...s:any[])=>lines.push(['move',...s]),lineTo:(...s:any[])=>lines.push(['line',...s]),stroke:()=>{},setLineDash:(s:any)=>dashes.push(s)};return {c:{getContext:()=>ctx} as any,text,lines,fills,dashes};}
test('game PNG contains compact dark summary with total time in the duration column',()=>{const {c,text,fills}=canvas();renderResultsPng(fixture('game'),c);assert.equal(fills[0][0],'#171a24');assert.ok(text.some(([s])=>s==='1 (2 rejected)'));assert.ok(text.some(([s])=>s==='Hard'));assert.ok(text.some(([s,x,y])=>s==='4.56'&&x===245&&y===431));assert.equal(text.some(([s])=>s==='Rejected reps'),false);assert.equal(text.some(([s])=>s==='Knee Angle'),false);assert.ok(c.height<700);});
test('test PNG preserves zero line, midpoint guide, signs and three charts',()=>{const {c,text,lines,dashes}=canvas();renderResultsPng(fixture('test'),c);for(const title of ['Knee Angle','Pelvic obliquity','Shoulder tilt'])assert.ok(text.some(([s])=>s===title));assert.equal(text.filter(([s])=>s==='0°').length,3);assert.ok(text.some(([s])=>s==='Varus (+)'));assert.ok(text.some(([s])=>s==='Valgus (−)'));assert.ok(lines.some(([kind,x])=>kind==='move'&&x===880));assert.ok(dashes.some(d=>d.length===0));assert.ok(dashes.some(d=>d.join(',')==='6,6'));});
